### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by cibere** [317070/python-twitch-stream#18]
When I import `from twitchstream.chat import TwitchChatStream`, I get this error.

**Comment by 317070** [comment]
What version of python are you on?

A quick Google search indicates that maybe you are trying to run this on Windows instead of Linux or Mac?
https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows

**Comment by 317070** [comment]
Looking back at the code, there is probably a more modern way in recent python versions to remove this dependency on             `fcntl.fcntl(s, fcntl.F_SETFL, os.O_NONBLOCK)`. You might want to try and remove the import line and that line and see if it just works.
