### ISSUE TITLE
If username is not all lowercase, it is able to send chat messages but cannot receive them.

### ISSUE THREAD

**Issue by NHDaly** [317070/python-twitch-stream#8]
For `TwitchChatStream`, if `username` has capital letters in it, the `chatstream.twitch_receive_messages()` doesn't ever return messages.

It is able to send messages, but not receive them.

Here is a simple example:

```
with TwitchChatStream(
      username=twitch_username,
      oauth=twitch_oauth,
      verbose=False) as chatstream:

  chatstream.join_channel('<my_lowercase_username>')
  print('connected to: ', chatstream.current_channel)

  chatstream.send_chat_message('Hello!')

  # The main loop to poll the chat.
  while True:
      received = chatstream.twitch_receive_messages()

      # process all the messages
      if received:
          print("received")
```

If `twitch_username` has capitals in it, the send succeeds but never receives messages, whereas if it's all lowercase, everything works. This even happens if i manually force `join_channel` to the lowercase named channel.

**Comment by RoboCD** [comment]
Thank you for noticing this, I thought I was going crazy when this didn't work.  One simple fix for this if it doesn't work, as in the color.py example, is to change line 42 to.
 `username = args.username.lower()`
This way it no longer matters whether it's capital or not.  Seems strange that it has to be lowercase.

**Comment by NHDaly** [comment]
Haha yeah I was too! Spent a while pretty upset. :)

Oooh, yes, great idea, @RoboCD. That's a good fix. :)

**Comment by NHDaly** [comment]
@RoboCD Which line 42 are you talking about?

**Comment by NHDaly** [comment]
I've sent a PR for updating the example in the README

**Comment by 317070** [comment]
Merged!
